### ISSUE TITLE
SQLAlchemy unable to find env variable with lowercase letters

### ISSUE THREAD

**Issue by XCanG** [dialoguemd/fastapi-sqla#39]
I make a simple setup with sqlite3, where I have env `SQLALCHEMY_URL = sqlite:///main.sqlite`, however during runtime I get an exception:
```
Traceback (most recent call last):
  File "C:\Python\Python38\lib\site-packages\starlette\routing.py", line 621, in lifespan
    async with self.lifespan_context(app):
  File "C:\Python\Python38\lib\site-packages\starlette\routing.py", line 518, in __aenter__
    await self._router.startup()
  File "C:\Python\Python38\lib\site-packages\starlette\routing.py", line 600, in startup
    handler()
  File "C:\Python\Python38\lib\site-packages\fastapi_sqla\__init__.py", line 66, in startup
    engine = engine_from_config(os.environ, prefix="sqlalchemy_")
  File "C:\Python\Python38\lib\site-packages\sqlalchemy\engine\create.py", line 754, in engine_from_config
    url = options.pop("url")
KeyError: 'url'
```
Digging a bit deeper I found that in SQLAlchemy `engine_from_config` use following code to get variable:
```py
options = dict(
    (key[len(prefix) :], configuration[key])
    for key in configuration
    if key.startswith(prefix)
)
```
where `configuration` is `os.environ` and prefix is `sqlalchemy_`, but when key is being iterated, it get capital `SQLALCHEMY_URL` which is not match for `key.startswith`, therefore before passing key it should be lowercased.

This line of code:
https://github.com/dialoguemd/fastapi-sqla/blob/2aa694edaf647eb5205f4500ef7dbe466d8a4106/fastapi_sqla/__init__.py#L64

can be replaced to this to fix this issue:
```py
engine = engine_from_config(dict((k.lower(), v) for k, v in os.environ.items() if k.lower().startswith("sqlalchemy_")), prefix="sqlalchemy_")
```

**Comment by hadrien** [comment]
Thanks @XCanG for raising that issue. Fixed by #40 and released in [v2.0.2](https://github.com/dialoguemd/fastapi-sqla/releases/tag/v2.0.2)
