### ISSUE TITLE
SQLAlchemy async support issues on fastapi_sqla.setup(app)

### ISSUE THREAD

**Issue by Alexsaphir** [dialoguemd/fastapi-sqla#51]
When trying to call setup to set a postgres database in async mode the code is not able to work.
main.py:
```python
import fastapi_sqla
from fastapi import FastAPI

app = FastAPI()
fastapi_sqla.setup(app)
```
I'm getting the following error:
```
zoterofast-ZF-Server-1  | INFO:     Started server process [10]
zoterofast-ZF-Server-1  | INFO:     Waiting for application startup.
zoterofast-ZF-Server-1  | ERROR:    Traceback (most recent call last):
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 621, in lifespan
zoterofast-ZF-Server-1  |     async with self.lifespan_context(app):
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 518, in __aenter__
zoterofast-ZF-Server-1  |     await self._router.startup()
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 600, in startup
zoterofast-ZF-Server-1  |     handler()
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi_sqla/__init__.py", line 73, in startup
zoterofast-ZF-Server-1  |     Base.prepare(engine)
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/ext/declarative/extensions.py", line 392, in prepare
zoterofast-ZF-Server-1  |     with inspection.inspect(engine)._inspection_context() as insp:
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/inspection.py", line 64, in inspect
zoterofast-ZF-Server-1  |     ret = reg(subject)
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 182, in _engine_insp
zoterofast-ZF-Server-1  |     return Inspector._construct(Inspector._init_engine, bind)
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 117, in _construct
zoterofast-ZF-Server-1  |     init(self, bind)
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 128, in _init_engine
zoterofast-ZF-Server-1  |     engine.connect().close()
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3210, in connect
zoterofast-ZF-Server-1  |     return self._connection_cls(self, close_with_result=close_with_result)
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
zoterofast-ZF-Server-1  |     else engine.raw_connection()
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3289, in raw_connection
zoterofast-ZF-Server-1  |     return self._wrap_pool_connect(self.pool.connect, _connection)
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3256, in _wrap_pool_connect
zoterofast-ZF-Server-1  |     return fn()
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 310, in connect
zoterofast-ZF-Server-1  |     return _ConnectionFairy._checkout(self)
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
zoterofast-ZF-Server-1  |     fairy = _ConnectionRecord.checkout(pool)
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
zoterofast-ZF-Server-1  |     rec = pool._do_get()
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
zoterofast-ZF-Server-1  |     with util.safe_reraise():
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
zoterofast-ZF-Server-1  |     compat.raise_(
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
zoterofast-ZF-Server-1  |     raise exception
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
zoterofast-ZF-Server-1  |     return self._create_connection()
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
zoterofast-ZF-Server-1  |     return _ConnectionRecord(self)
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
zoterofast-ZF-Server-1  |     self.__connect()
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 665, in __connect
zoterofast-ZF-Server-1  |     with util.safe_reraise():
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
zoterofast-ZF-Server-1  |     compat.raise_(
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
zoterofast-ZF-Server-1  |     raise exception
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
zoterofast-ZF-Server-1  |     self.dbapi_connection = connection = pool._invoke_creator(self)
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 590, in connect
zoterofast-ZF-Server-1  |     return dialect.connect(*cargs, **cparams)
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 597, in connect
zoterofast-ZF-Server-1  |     return self.dbapi.connect(*cargs, **cparams)
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 777, in connect
zoterofast-ZF-Server-1  |     await_only(self.asyncpg.connect(*arg, **kw)),
zoterofast-ZF-Server-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 67, in await_only
zoterofast-ZF-Server-1  |     raise exc.MissingGreenlet(
zoterofast-ZF-Server-1  | sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)
zoterofast-ZF-Server-1  | 
zoterofast-ZF-Server-1  | ERROR:    Application startup failed. Exiting.
zoterofast-ZF-Server-1  | sys:1: RuntimeWarning: coroutine 'connect' was never awaited
zoterofast-ZF-Server-1  | RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
*pyproject.toml deps*
```toml
[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^0.20.0"
asyncio = "^3.4.3"

poethepoet = "^0.13.1"

loguru = "^0.6.0"
sentry-sdk = "^1.5.8"

fastapi = "^0.75.0"
typer = "^0.4.0"
uvicorn = "^0.17.6"
gunicorn = "^20.1.0"


fastapi-sqla = "^2.3.1"
fastapi-offline = "^1.3.2"

sqlalchemy = "^1.4.32"
psycopg2-binary = "^2.9.3"
asyncpg = "^0.25.0"

pydantic = {extras = ["dotenv"], version = "^1.9.0"}
ujson = "^5.1.0"
email-validator = "^1.1.3"

alembic = "^1.7.7"


requests = "^2.27.1"
Jinja2 = "^3.1.1"
python-multipart = "^0.0.5"
itsdangerous = "^2.1.2"
PyYAML = "^6.0"
```

**Comment by hadrien** [comment]
Thanks for opening an issue, I'll check this today.

**Comment by hadrien** [comment]
I have been able to reproduce when setting `sqlalchemy_url` environment variable to an asyncpg dialect URI: `postgresql+asyncpg://postgres@localhost` 

Actually, to use `asyncpg`, you'll need to set 2 environment variables:
1. `sqlalchemy_url` using `postgresql` dialect, i.e: `postgresql://postgres@localhost`
2. `async_sqlalchemy_url` using `postgresql+asyncpg` dialect, i.e: `postgresql+asyncpg://postgres@localhost` 

The first one will be used to reflect all declarative mapping classes declared. Currently, sqlalchemy does not allow using an async engine to run that reflection.

Please, tell me if it fixes your issue @Alexsaphir. Thanks.

**Comment by Alexsaphir** [comment]
Sorry for the late response. Setting up the env variable with postgresql URI, fixed it.
