### ISSUE TITLE
sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here

### ISSUE THREAD

**Issue by abnerjacobsen** [dialoguemd/fastapi-sqla#56]
Hello,

Thanks for your module for FastApi, of all the solutions for accessing a Postgres DB that I've researched so far I think it's the closest to what I think is the best solution.

But, now on to my problem: I created a local development test project that uses Uvicorn to run my FastApi app and when it starts up the following error occurs:

```bash
sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)

ERROR:    Application startup failed. Exiting.
sys:1: RuntimeWarning: coroutine 'connect' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

I run my program like this:

`python3 ./daschat_integration_mautic/uvicorn_wsgi2.py`

And the /daschat_integration_mautic/uvicorn_wsgi2.py file has the following content:

```python
# -*- coding: utf-8 -*-
"""Application Web Server Gateway Interface - uvicorn."""
import os
import sys
import uvicorn
from loguru import logger

from daschat_integration_mautic.config.settings import settings

from daschat_integration_mautic.utils.uvicorn_loguru_integration import (
    run_uvicorn_loguru,
)


def main():
    run_uvicorn_loguru(
        uvicorn.Config(
            "daschat_integration_mautic.app.teste1:app",
            host="0.0.0.0",
            port=8000,
            log_level=settings.LOG_LEVEL,
            reload=True,
            workers=1,
        )
    )

if __name__ == "__main__":
    main()
```

And the app daschat_integration_mautic.app.teste1:app that is called by Uvicorn has the following content:

```python
from fastapi import APIRouter, Depends
from fastapi_sqla import Session
from fastapi_sqla.asyncio_support import AsyncSession

import fastapi_sqla
from fastapi import FastAPI

app = FastAPI()
fastapi_sqla.setup(app)

router = APIRouter()


@router.get("/example")
def example(session: Session = Depends()):
    return session.execute("SELECT now()").scalar()


@router.get("/async_example")
async def async_example(session: AsyncSession = Depends()):
    return await session.scalar("SELECT now()")
```

Do you have any idea what the problem is?

thanks

**Comment by hadrien** [comment]
Sorry for the delay of my answer, checking this right now.

**Comment by hadrien** [comment]
@abnerjacobsen Do you still have the issue despite my answer?

**Comment by abnerjacobsen** [comment]
@hadrien Yes, it did not work.

I tested with this code:

```
from fastapi import FastAPI, APIRouter, Depends
from fastapi_sqla import Session, setup
from fastapi_sqla.asyncio_support import AsyncSession

app = FastAPI()
setup(app)

router = APIRouter()
app.mount("/", router)

@router.get("/example")
def example(session: Session = Depends()):
    return session.execute("SELECT now()").scalar()


@router.get("/async_example")
async def async_example(session: AsyncSession = Depends()):
    return await session.scalar("SELECT now()")

```
with:

[uvicorn teste1:app](url)

And got this error:

```
INFO:     Started server process [10113]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/starlette/routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/starlette/routing.py", line 530, in __aenter__
    await self._router.startup()
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/starlette/routing.py", line 614, in startup
    handler()
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/fastapi_sqla/__init__.py", line 73, in startup
    Base.prepare(engine)
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/ext/declarative/extensions.py", line 397, in prepare
    with inspection.inspect(engine)._inspection_context() as insp:
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/inspection.py", line 64, in inspect
    ret = reg(subject)
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 182, in _engine_insp
    return Inspector._construct(Inspector._init_engine, bind)
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 117, in _construct
    init(self, bind)
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 128, in _init_engine
    engine.connect().close()
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 777, in connect
    await_only(self.asyncpg.connect(*arg, **kw)),
  File "/home/abner/Devel/daschat/services/daschat_integration_mautic/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 59, in await_only
    raise exc.MissingGreenlet(
sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)

ERROR:    Application startup failed. Exiting.
sys:1: RuntimeWarning: coroutine 'connect' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```


My installed packages are:

[Package                    Version
-------------------------- ---------
aiobotocore                2.4.0
aiohttp                    3.8.1
aioitertools               0.10.0
aioredis                   2.0.1
aioresponses               0.7.3
aiosignal                  1.2.0
anyio                      3.6.1
asgiref                    3.5.2
async-timeout              4.0.2
asyncpg                    0.26.0
attrs                      22.1.0
black                      21.12b0
botocore                   1.27.59
certifi                    2022.6.15
chardet                    4.0.0
charset-normalizer         2.1.1
click                      8.0.4
coverage                   6.4.4
cuid                       0.3
daschat-base               0.15.10
daschat-integration-mautic 0.1.0
dnspython                  2.2.1
email-validator            1.2.1
fastapi                    0.81.0
fastapi-sqla               2.3.6
flake8                     3.9.2
flake8-docstrings          1.6.0
flake8-import-order        0.18.1
flake8-todo                0.7
frozenlist                 1.3.1
fsspec                     2022.8.2
greenlet                   1.1.3
gunicorn                   20.1.0
h11                        0.13.0
httptools                  0.4.0
idna                       2.10
iniconfig                  1.1.1
Jinja2                     3.1.2
jmespath                   1.0.1
loguru                     0.5.3
mangum                     0.15.1
MarkupSafe                 2.1.1
mccabe                     0.6.1
mock                       4.0.3
multidict                  6.0.2
mypy-extensions            0.4.3
packaging                  21.3
pathspec                   0.9.0
pendulum                   2.1.2
pip                        22.0.3
platformdirs               2.5.2
pluggy                     1.0.0
py                         1.11.0
pycodestyle                2.7.0
pydantic                   1.9.2
pydocstyle                 6.1.1
pyflakes                   2.3.1
pyparsing                  3.0.9
pytest                     6.2.5
pytest-asyncio             0.15.1
pytest-cov                 2.12.1
python-dateutil            2.8.2
python-dotenv              0.20.0
pytz                       2021.3
pytzdata                   2020.1
PyYAML                     6.0
requests                   2.25.1
s3fs                       2022.8.2
setproctitle               1.3.2
setuptools                 60.6.0
six                        1.16.0
sniffio                    1.2.0
snowballstemmer            2.2.0
SQLAlchemy                 1.4.40
stackprinter               0.2.8
starlette                  0.19.1
structlog                  22.1.0
toml                       0.10.2
tomli                      1.2.3
typing_extensions          4.3.0
urllib3                    1.26.12
uvicorn                    0.17.6
uvloop                     0.16.0
watchgod                   0.8.2
websockets                 10.3
wheel                      0.37.1
wrapt                      1.14.1
xxhash                     2.0.2
yarl                       1.8.1](url)

**Comment by hadrien** [comment]
@abnerjacobsen did you define the environment variable `async_sqlalchemy_url`?

**Comment by abnerjacobsen** [comment]
Yes,  I have defined booth the env variables.

**Comment by hadrien** [comment]
<details><summary>@abnerjacobsen I was able to reproduce:</summary>

```bash
❯ sqlalchemy_url=postgresql+asyncpg://postgres@localhost uvicorn main:app
INFO:     Started server process [28738]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "starlette/routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "starlette/routing.py", line 530, in __aenter__
    await self._router.startup()
  File "starlette/routing.py", line 614, in startup
    handler()
  File "/Users/hadrien/W/fastapi-sqla/./fastapi_sqla/__init__.py", line 73, in startup
    Base.prepare(engine)
  File "sqlalchemy/ext/declarative/extensions.py", line 397, in prepare
    with inspection.inspect(engine)._inspection_context() as insp:
  File "sqlalchemy/inspection.py", line 64, in inspect
    ret = reg(subject)
  File "sqlalchemy/engine/reflection.py", line 182, in _engine_insp
    return Inspector._construct(Inspector._init_engine, bind)
  File "sqlalchemy/engine/reflection.py", line 117, in _construct
    init(self, bind)
  File "sqlalchemy/engine/reflection.py", line 128, in _init_engine
    engine.connect().close()
  File "sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "sqlalchemy/pool/base.py", line 320, in connect
    return _ConnectionFairy._checkout(self)
  File "sqlalchemy/pool/base.py", line 884, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "sqlalchemy/pool/base.py", line 486, in checkout
    rec = pool._do_get()
  File "sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "sqlalchemy/pool/base.py", line 266, in _create_connection
    return _ConnectionRecord(self)
  File "sqlalchemy/pool/base.py", line 381, in __init__
    self.__connect()
  File "sqlalchemy/pool/base.py", line 677, in __connect
    with util.safe_reraise():
  File "sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "sqlalchemy/pool/base.py", line 673, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "sqlalchemy/dialects/postgresql/asyncpg.py", line 780, in connect
    await_only(self.asyncpg.connect(*arg, **kw)),
  File "sqlalchemy/util/_concurrency_py3k.py", line 59, in await_only
    raise exc.MissingGreenlet(
sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)

ERROR:    Application startup failed. Exiting.
sys:1: RuntimeWarning: coroutine 'connect' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

</details>

If I am correct, the `sqlalchemy_url` you've set uses a scheme like `postgresql+asyncpg://` (like `postgresql+asyncpg://postgres@localhost`).

**Why it fails** 

`fastapi-sqla` will call SQLAlchemy to reflect the table in the database using that url. 

BUT, SQLAlchemy will fail as `[DeferredReflection.prepare](https://docs.sqlalchemy.org/en/14/orm/extensions/declarative/index.html?highlight=prepare#sqlalchemy.ext.declarative.DeferredReflection.prepare)` fails when using an `async` dialect. 

I'll open a PR so the error raised is meaningful.

**How you can fix this**

Define 2 envvars:
* `sqlalchemy_url=postgresql://postgres@localhost` using a synchronous dialect, you may need to install psycopg2. This will allow reflecting tables at startup
* `async_sqlalchemy_url=postgresql+asyncpg://postgres@localhost` using an async dialect. This will allow using an async session and fixtures.

Disclaimer: async support is in beta, I'll make sure to surface this in the README.

**Comment by hadrien** [comment]
@abnerjacobsen If you confirm that my analysis is correct, I have a fix in mind.

**Comment by abnerjacobsen** [comment]
@hadrien Yes, with the 2 envvars defined as you suggested the problem was solved.

I ran the following program with a base of 130,000 contacts and another of notifications with more than 400,000 records and the listing queries and pagination worked correctly:

```
from fastapi import Depends, FastAPI, HTTPException, APIRouter
from fastapi_sqla import Base, Item, Page, Pagination, Session, setup, Paginate
from fastapi_sqla.asyncio_support import AsyncSession
from pydantic import BaseModel, EmailStr
from sqlalchemy import select, DateTime, func, select
from sqlalchemy.exc import IntegrityError
from typing import Optional, List

app = FastAPI()
setup(app)

class Channels(BaseModel):
    uid: Optional[str] = None
    type: Optional[str] = None
    status: Optional[int] = 1

class User(Base):
    __tablename__ = "contacts"

class UserIn(BaseModel):
    entity_id: Optional[str] = None
    id: Optional[str] = None
    citizen_id: Optional[str] = None
    name: Optional[str] = None
    gender: Optional[str] = None
    channels: Optional[List[Channels]] = []


class UserModel(UserIn):
    id: str

    class Config:
        orm_mode = True


class Notification(Base):
    __tablename__ = "notifications"


class NotificationIn(BaseModel):
    entity_id: Optional[str] = None
    id: Optional[str] = None
    channels: List[Channels]


class NotificationModel(NotificationIn):
    id: str

    class Config:
        orm_mode = True

async def query_count(session: Session = Depends()) -> int:
    return session.execute(select(func.count()).select_from(User)).scalar()


CustomPaginate = Pagination(min_page_size=10, max_page_size=100, query_count=query_count)

router = APIRouter()

@app.get("/all_users", response_model=Page[UserModel])
async def all_users(paginate: CustomPaginate = Depends()):
    return paginate(select(User))

@app.get("/users", response_model=Page[UserModel])
async def list_users(paginate: Paginate = Depends()):
    return paginate(select(User))

@app.get("/notifications", response_model=Page[NotificationModel])
async def list_notifications(paginate: Paginate = Depends()):
    return paginate(select(Notification))

@app.get("/users/{id}", response_model=Item[UserModel])
def get_user(id: str, session: Session = Depends()):
    query = select(User).where(User.id == id)
    user = session.execute(query).scalars().all()
    if user is None:
        raise HTTPException(404)
    return {"data": user}
```
I just couldn't make the query of 1 individual record work, the one in this code snippet:

```
@app.get("/users/{id}", response_model=Item[UserModel])
def get_user(id: str, session: Session = Depends()):
    query = select(User).where(User.id == id)
    user = session.execute(query).scalars().all()
    if user is None:
        raise HTTPException(404)
    return {"data": user}
```

When I run it the following error occurs:

```
pydantic.error_wrappers.ValidationError: 1 validation error for Item[UserModel]
response -> data -> id
  field required (type=value_error.missing)
```

As I'm still not familiar with the Sqlalchemy 1.4 ORM I must be making some mistake. Do you have any suggestion to solve it?

**Comment by hadrien** [comment]
> @hadrien Yes, with the 2 envvars defined as you suggested the problem was solved.

Great to read.

***** 
### Pagination
FYI, fastapi-sqla pagination is run using a blocking session, not an async one, therefore you should remove the `async` keyword on the paginated functions. `fastapi-sqla` should provide an `AsyncPaginate` to allow such use case. Sorry, it is not documented yet:

> ```python
> def query_count(session: Session = Depends()) -> int:
>     return session.execute(select(func.count()).select_from(User)).scalar()
> 
> def all_users(paginate: CustomPaginate = Depends()):
>     return paginate(select(User))
> 
> @app.get("/users", response_model=Page[UserModel])
> def list_users(paginate: Paginate = Depends()):
>     return paginate(select(User))
> 
> @app.get("/notifications", response_model=Page[NotificationModel])
> def list_notifications(paginate: Paginate = Depends()):
>     return paginate(select(Notification))
> ```

*****
### Pydantic error

> ```python
> @app.get("/users/{id}", response_model=Item[UserModel])
> def get_user(id: str, session: Session = Depends()):
>     query = select(User).where(User.id == id)
>     user = session.execute(query).scalars().all()
> ```

^ user will hold a **list** as it calls [`.all()`](https://docs.sqlalchemy.org/en/14/core/connections.html?highlight=all#sqlalchemy.engine.ScalarResult.all) 

But the endpoint response model is `Item[UserModel]` so pydantic will parse **one `UserModel` entity**.


> ```
> pydantic.error_wrappers.ValidationError: 1 validation error for Item[UserModel]
> response -> data -> id
>   field required (type=value_error.missing)
> ```

^ `list` do not have an `id` attribute

Try using [`one_or_none()`](https://docs.sqlalchemy.org/en/14/core/connections.html?highlight=all#sqlalchemy.engine.ScalarResult.one_or_none) this instead:

```python
@app.get("/users/{id}", response_model=Item[UserModel])
def get_user(id: str, session: Session = Depends()):
    query = select(User).where(User.id == id)
    user = session.execute(query).scalars(). one_or_none()
    if user is None:
        raise HTTPException(404)
    return {"data": user}
```

**Comment by abnerjacobsen** [comment]
@hadrien Thanks a lot, all working fine now.

Now I'm going to test using AWS Lambda with Mangum, which is how my app runs when in production. I'll post the results here today or at the latest tomorrow.

Regarding pagination, adding an AsyncPaginate module to fastapi-sqla would be an interesting and very useful addition. I intend to use your module in a healthcare application that we have and that has a high volume of database access, any gain in the use of database resources is important.

Regards,

**Comment by abnerjacobsen** [comment]
@hadrien Just to let you know, I tested the script below deployed with Serverless Framework on AWS Lambda using Mangum as ASGI handler and it worked correctly with a small hack to solve a Mangum issue that occurs at Fastapi startup regarding asynchronous middlewares:

```
import asyncio
from fastapi import Depends, FastAPI, HTTPException, APIRouter
from fastapi_sqla import Base, Item, Page, Pagination, Session, setup, Paginate
from fastapi_sqla.asyncio_support import AsyncSession
from pydantic import BaseModel, EmailStr
from sqlalchemy import select, DateTime, func, select, and_, or_
from sqlalchemy.exc import IntegrityError
from typing import Optional, List
from mangum import Mangum

app = FastAPI(title="Rute Digital",description="Serviços da Rute para você.",version="v1",docs_url="/docs", redoc_url=None)
setup(app)

class Channels(BaseModel):
    uid: Optional[str] = None
    type: Optional[str] = None
    status: Optional[int] = 1

class User(Base):
    __tablename__ = "contacts"

class UserIn(BaseModel):
    entity_id: Optional[str] = None
    id: Optional[str] = None
    citizen_id: Optional[str] = None
    name: Optional[str] = None
    gender: Optional[str] = None
    channels: Optional[List[Channels]] = []


class UserModel(UserIn):
    id: str

    class Config:
        orm_mode = True


class Notification(Base):
    __tablename__ = "notifications"


class NotificationIn(BaseModel):
    entity_id: Optional[str] = None
    id: Optional[str] = None
    channels: List[Channels]


class NotificationModel(NotificationIn):
    id: str

    class Config:
        orm_mode = True

def query_count(session: Session = Depends()) -> int:
    return session.execute(select(func.count()).select_from(User)).scalar()

CustomPaginate = Pagination(min_page_size=10, max_page_size=100, query_count=query_count)

router = APIRouter()

@app.get("/all_users", response_model=Page[UserModel])
def all_users(paginate: CustomPaginate = Depends()):
    return paginate(select(User))

@app.get("/users", response_model=Page[UserModel])
def list_users(paginate: Paginate = Depends()):
    return paginate(select(User))

@app.get("/notifications", response_model=Page[NotificationModel])
def list_notifications(paginate: Paginate = Depends()):
    return paginate(select(Notification))

@app.get("/users/{entity_id}/{id}", response_model=Item[UserModel])
def get_user(entity_id: str, id: str, session: Session = Depends()):
    query = select(User).where(User.entity_id == entity_id, User.id == id)
    # query = select(User).where(and_(User.entity_id == entity_id, User.id == id))
    print(query)
    user = session.execute(query).scalars().one_or_none()
    if user is None:
        raise HTTPException(404)
    return {"data": user}

# Bug in Mangun when using with custom lifespan-aware middleware.
# This is a little hack from:
# https://github.com/jordaneremieff/mangum/discussions/211
# The trick is to use lifespan="off" and and run 
# Fastapi startup function manually
aws_handler = Mangum(app, lifespan="off")
loop = asyncio.get_event_loop()
loop.run_until_complete(app.router.startup())
```

Without this trick, with every incoming HTTP request Fastapi runs fastapi-sqla startup again and again:

```
aws_handler = Mangum(app, lifespan="off")
loop = asyncio.get_event_loop()
loop.run_until_complete(app.router.startup())
```

I found the tip in this thread: https://github.com/jordaneremieff/mangum/discussions/211

**Comment by hadrien** [comment]
FYI @abnerjacobsen, I've started the implementation for async pagination (#64), stay tuned. :-)

**Comment by hadrien** [comment]
@abnerjacobsen Async pagination 👉🏽 https://github.com/dialoguemd/fastapi-sqla#async-pagination
